### ISSUE TITLE
Choosing llama3.2:1b

### ISSUE THREAD

**Issue by RRR3d** [SirUli/homeassistant-ollama-addon#53]
Thanks for your great work , I would like to ask is there an option that we can access it using some how a terminal or how can i choose llama3.2:1b instead of using llama3.2

**Comment by SirUli** [comment]
This image just offers the API, nothing else. Indeed all the tools on the ollama side would continue to work - please take a look at the [API description](https://github.com/ollama/ollama/blob/main/docs/api.md) for further details.

Does that answer your question?
